sonata_admin:
    title: 'Zizoo Admin'
    options:
        html5_validate: true
        use_select2: false
        use_icheck: false
    assets:
        extra_javascripts: 
            - 'bundles/admin/js/custom.js'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
