version: '3'
services:
    mysql:
        image: "mysql:5.7"
        restart: always
        environment: 
            - MYSQL_ROOT_PASSWORD="root"
    web:
        build: .
        restart: always
        ports:
            - "8002:8000"
        environment: 
            - DATABASE_URL="mysql://root:root@mysql:3306/zizoo?serverVersion=5.7"
        command: bash -c "php bin/console doctrine:database:create && php bin/console doctrine:migrations:migrate"
        depends_on:
            - mysql